spring.application.name=notify
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.group-id=notify-system
spring.data.redis.cluster.nodes=${REDIS_CLUSTER_NODES:localhost:6379,localhost:6380,localhost:6381}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
notify.datasource.routing-enabled=${NOTIFY_DB_ROUTING_ENABLED:false}
notify.datasource.write-url=${NOTIFY_DB_WRITE_URL:jdbc:postgresql://localhost:5432/notify}
notify.datasource.read-url=${NOTIFY_DB_READ_URL:jdbc:postgresql://localhost:5433/notify}
notify.datasource.username=${NOTIFY_DB_USERNAME:notify}
notify.datasource.password=${NOTIFY_DB_PASSWORD:notify}
notify.kafka.topics.user-operation-events=user-operation-events
notify.kafka.topics.notification-events=notification-events
notify.kafka.topics.user-operation-events-dlt=user-operation-events-dlt
notify.kafka.topics.notification-events-dlt=notification-events-dlt
notify.deduplication.default-window=10s
notify.window.default-size=30s
notify.window.default-shard-size=10s
